            Line:                                                                
                id: l0                                                           
                bezier: [root.center_x - 100, 50, root.center_x + 50, 100, root.center_x + 200, 50]
                width: 2                                                         
                                                                                 
            Line:                                                                
                id: l1                                                           
                bezier: [root.center_x + 50, 70, root.center_x + 50, 500]        
                width: 2                                                         
            Line:                                                                
                id: l2                                                           
                bezier: [root.center_x + 50, 500, self.center_x + 250, 500]      
                width: 2                                                         
            Line:                                                                
                id: l3                                                           
                bezier: [root.center_x + 250, 500, self.center_x + 250, 400]     
                width: 2                                                         
            Line:                                                                
                id: l4                                                           
                circle: [root.center_x + 250, 350, 50]                           
                width: 2                                                         
            Line:                                                                
                id: l5                                                           
                points: [root.center_x + 250, 300, self.center_x + 250, 150]     
                width: 2                                                         
            Line:                                                                
                id: l6                                                           
                points: [root.center_x + 250, 150, self.center_x + 330, 120]     
                width: 2                                                         
            Line:                                                                
                id: l7                                                           
                points: [root.center_x + 250, 150, self.center_x + 170, 120]     
                width: 2                                                         
            Line:                                                                
                id: l8                                                           
                points: [root.center_x + 250, 250, self.center_x + 330, 170]     
                width: 2                                                         
            Line:                                                                
                id: l9                                                           
                points: [root.center_x + 250, 250, self.center_x + 170, 170]     
                width: 2                                                         

                
