<MyWidget>:
    FloatLayout:
        Image:
            id: hangman_img
            source: '0.png'
            size_hint: None, None
            size: root.height, root.width / 2
            pos_hint: {'center_x': 0.75, 'center_y': 0.5}

        Label:
            id: word_status
            font_size: 50
            text: '_ _ _ _ _'
            pos_hint: {'center_x': 0.2, 'center_y': 0.8}

        Label:
            id: guessed_letters
            font_size: 50
            text: 'A, B, C'
            pos_hint: {'center_x': 0.2, 'center_y': 0.4}

        Label:
            id: game_over
            pos_hint: {'center_x': 0.5, 'y': 0.6}
            font_size: 100
            text: ''
            pos_hint: {'center_x': 0.5, 'center_y': 0.1}

<GameView>:
    MyWidget: